#VAADIN
vaadin.launch-browser=true

#POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/kamann
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#APPLICATION
spring.application.name=kamann
