package pl.kamann.config.codes;

public enum RecurrenceCodes {
    DAYS_OF_WEEK_REQUIRED,
    RECURRENCE_END_DATE_REQUIRED,
    RECURRENCE_END_DATE_AFTER_START_DATE,
    RECURRENCE_END_TIME_AFTER_START_TIME,
    PARTICIPANTS_EXCEED_MAX,
    RECURRENCE_RULE_REQUIRED, INVALID_RECURRENCE_RULE, START_IN_PAST, INVALID_TIME_ORDER, INVALID_UNTIL_DATE, TIME_REQUIRED, START_DATE_REQUIRED, INVALID_TIMEZONE, INVALID_DURATION, FREQUENCY_REQUIRED
}
